### PR TITLE
EZP-32105: Use search.pagination.limit parameter instead of obsolete pagination.search_limit

### PR DESCRIPTION
**Pull request by kmadejski**
| Question      | Answer
| ------------- | ---
| Tickets       |  [EZP-32105](https://jira.ez.no/browse/EZP-32105)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes/no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-search/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)

### CODE REVIEW

**Review by adamwojs — APPROVED** [review]

**Review by lserwatka — APPROVED** [review]

**Review by Steveb-p — APPROVED** [review]

**Review by ViniTou — APPROVED** [review]
But can we also get additional PR to adminUI with deprecating old configuration?

**Review by mikadamczyk — APPROVED** [review]

**Review by mnocon — CHANGES_REQUESTED** [review]
I think the parameter has to be changed here as well:
https://github.com/ezsystems/ezplatform-search/blob/1.0/src/lib/View/SearchViewFilter.php#L76

otherwise I had exceptions when accesing the search on other SiteAccess than `site`  (for example: example.com/pol/search )
With the change I've mentioned above it works for me, but only if I define:
```
parameters:
    ezsettings.site_group.search_view:
        full:
            default:
                template: "@@ezdesign/search/index.html.twig"
                match: []
```
(similar as https://github.com/ezsystems/ezplatform-search/blob/master/src/bundle/Resources/config/default_settings.yaml#L4 but for `site_group` where my SiteAccesses are).

Q: If I define the view for `default` scope (`ezsettings.default.search_view`) then the template for AdminUI is overridden as well and AdminUI search stops working - is it a misconfiguration on my side/a bug in the product somehow related to scopes?

**Comment by kmadejski** [comment]
Thanks, @mnocon! I have fixed this another occurence you've found. Could you please re-test?

> Q: If I define the view for default scope (ezsettings.default.search_view) then the template for AdminUI is overridden as well and AdminUI search stops working - is it a misconfiguration on my side/a bug in the product somehow related to scopes?

I adapted it to `site_group` as this solves the problem for a clean installation. Your observation is indeed very interesting though, as AdminUI should (re)define this template on its own (I guess for `admin_group`) and therefore this `default` configuration should not interfere with it. If it behaves differently then we might have a bug, even so it is not directly related to this PR.

**Review by mnocon — APPROVED** [review]
@kmadejski looks good now!

I've reported the other thing I've mentioned in a separate ticket: https://jira.ez.no/browse/EZP-32121

**Comment by lserwatka** [comment]
You can merge it up.

**Comment by kmadejski** [comment]
@lserwatka done in https://github.com/ezsystems/ezplatform-search/commit/a9d2574df7ad843be7b7b11ab4abe0dc3773037b.

**Pull request merged**
